alias apse='sudo aptitude search'
alias apin='sudo aptitude -y install '
alias apup='sudo apt-get update'
alias apupg='sudo apt-get upgrade'
alias apupand='sudo apt-get -y update && sudo apt-get -y upgrade'
alias apremv='sudo apt-get remove'
alias aprein='sudo aptitude reinstall'
alias dl='dpkg -l'
alias dlgr='dpkg -l | grep'
alias psg='ps ax | grep'
alias clamdo='clamscan -r ~/download'
alias clamho='clamscan --recursive=no ~/'
alias auclen='sudo apt-get -y autoclean'
alias auremv='sudo apt-get -y autoremove'
alias pgremv='sudo apt-get --purge remove'
alias aurora='~/ProgramFiles/firefox_aurora/firefox -P default'
alias mpsyoutube='cd ~/forselfbuild/mps-youtube/ && sudo docker run -v /dev/snd:/dev/snd -it --rm --privileged --name mpsyt mpsyt'
